name: Test Score Calculator
on: [push]
jobs:
  test-score-calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run tests
        run: |
          python -c "
            from score_calculator import calculate_average_score, calculate_average_score_for_all_subjects
            
            students = {
                'John': {
                    'Math': ['good', 'very good'],
                    'Science': ['excellent']
                }
            }
            
            calculate_average_score(students)
            calculate_average_score_for_all_subjects(students)
          "
